name: Go package

on:
  workflow_dispatch:
    inputs:
      go_version:
        description: "Go SDK version"
        required: true
        default: "1.18"
        type: choice
        options:
          - "1.16"
          - "1.17"
          - "1.18"

  push:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: "Go version"
        run: echo "${{inputs.go_version}}"

      - uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: "${{inputs.go_version}}"

      - name: Build
        run: go build -v ./...

      - name: Test
        run: go test -v ./...
